### ISSUE TITLE
fmt::sprintf() is triggering the libc sprintf() rule

### ISSUE THREAD

**Issue by markgalassi** [kunaltyagi/nsiqcppstyle#18]
The fmt library in C++ offers a streamlined implementation of the boost::format libraries.  Among other things it offers an sprintf() function.  This function safely  generates an std::string without buffer overflow issues.

nsiqcppstyle reports:
`
Do not use burfferoverflow risky function(sprintf [RULE_10_1_A_do_not_use_bufferoverflow_risky_function_for_unix] `

for this line of code:

`  string s = fmt::sprintf("%2s%012.8f", year, doy_fraction);`

The simple solution might be to check if sprintf( is preceded by a "::" (two colons), although that would run in to problems if you have "using namespace fmt;" and thus drop the fmt::.  Still, I think it would be quite OK.

**Comment by kunaltyagi** [comment]
Checking for fmt::sprintf would imply checking for library specific quirks (despite making it generic). That's because there's [std::sprintf](https://en.cppreference.com/w/cpp/io/c/fprintf) which will escape this.

I understand the rationale behind your suggestion, just that a good solution will not be scalable for this project. Maybe you could implement a different rule for your{self, organization} and make it an alternative to this one (available via opt-in). I welcome such contributions.

Or you could use some other checker that brings a lot more of semantic knowledge power to the rules such as `clang-tidy`.

**Comment by kunaltyagi** [comment]
Note: I'll take a look at the patch sometime next week. I'll be traveling soon and can't promise any action til next Wednesday at minimum.

> the whole existence of RULE_10_1_A is all about quirks

That's a nice way (too nice) to look at it, but sadly, C doesn't consider them as quirks. It'd be easy to mark functions as deprecated, but C just wouldn't. And in turn we the programmers have to do "hacks" and tooling around the language.

> it is one of the most useful rules

Thanks for your kind words. May I ask how you use this tool in your current setup?

**Comment by markgalassi** [comment]
You asked

> May I ask how you use this tool in your current setup?

In Los Alamos we have a large simulation program related to space research.  We have somewhere between 1/3 and 1/2 a million lines of C++ code.  We are using nsiqcppstyle to enforce a uniform style, so that people joining the project don't get whiplash going from one chunk of code to another.  We have found nsiqcppstyle quite valuable, although hard to pronounce when we talk about it :-)

**Comment by kunaltyagi** [comment]
Thanks for that. I've been struggling to see the scope of the project due to lack of ways to connect with the community.
