### ISSUE TITLE
Write XML Uses Binary instead of String

### ISSUE THREAD

**Issue by NitenIchiry** [kunaltyagi/nsiqcppstyle#46]
In function `PrepareReport` the open functions try to open the files as binaries. This leads to problems, when the output xml/csv is chosen. I think this is python 2 style ? Think about using `csvfile = open(outputPath, "w")`. This fixed it for me

**Comment by mosherubin** [comment]
@NitenIchiry That is a good catch!  For the record, when porting NsiqCppStyle from Python 2 to 3, the original code was:

`csvfile = file(outputPath, "wb")`

Python 3 deprecated the `file` function in favor of `open`, so the fix was made.  The original code, however, used a mode of '`wb`', and I slavishly left it in place.

Can you please submit a pull request with your change for kunaltyagi to review and merge in?

Thanks!

Moshe
